// Generated by `python -m src.schema_export swift` — do not edit.
// Mirrors GET /daily on the health-tracker-ingest service.
// Every field is Optional because a blank cell means NOT MEASURED, which
// is different from zero — never default these to 0.

import Foundation

/// Self-reported
struct SelfReport: Codable, Hashable {
    /// TRUE if I had a bowel movement on this day; blank means none was logged (not necessarily none happened). Set from a plain text note. Digestion lags intake by roughly a day.
    /// measures: reported about this date
    var bowelMovement: Bool?

    enum CodingKeys: String, CodingKey {
        case bowelMovement = "bowel_movement"
    }
}

/// Sleep (Fitbit, night that ended this morning)
struct Sleep: Codable, Hashable {
    /// Minutes actually asleep. The headline sleep number.
    /// measures: the night that ended on this morning [min]
    var sleepMins: Int?
    /// sleep_mins / time_in_bed_mins. Above ~90% is good. This is the honest stand-in for Fitbit's proprietary sleep score, which the Google Health API does not expose at all.
    /// measures: the night that ended on this morning [%]
    var sleepEfficiencyPct: Double?
    /// Deep (slow-wave) sleep. Physical restoration; suppressed by alcohol and late eating. Typically 13-23% of the night.
    /// measures: the night that ended on this morning [min]
    var sleepDeepMins: Int?
    /// REM sleep. Cognitive/emotional consolidation. Typically 20-25% of the night.
    /// measures: the night that ended on this morning [min]
    var sleepRemMins: Int?
    /// Total sleep period: asleep + awake time in bed.
    /// measures: the night that ended on this morning [min]
    var timeInBedMins: Int?
    /// Light sleep. The bulk of the night; not itself a quality signal.
    /// measures: the night that ended on this morning [min]
    var sleepLightMins: Int?
    /// Minutes awake during the sleep period (fragmentation).
    /// measures: the night that ended on this morning [min]
    var sleepAwakeMins: Int?
    /// Minutes taken to fall asleep. Long latency often follows a late or heavy meal, caffeine, or a stressful day.
    /// measures: the night that ended on this morning [min]
    var sleepLatencyMins: Int?
    /// Number of distinct awake episodes during the night.
    /// measures: the night that ended on this morning [count]
    var sleepAwakenings: Int?
    /// Local clock time I fell asleep (usually the previous evening). Consistency of this time matters more than its value.
    /// measures: the night that ended on this morning [HH:MM]
    var sleepStart: String?
    /// Local clock time I woke on this morning.
    /// measures: the night that ended on this morning [HH:MM]
    var sleepEnd: String?
    /// Daytime sleep, kept deliberately apart from the night figures: a nap ends on the same wake-day as a night and would otherwise corrupt it. Note the window is this DAY, unlike every other sleep column.
    /// measures: reported about this date [min]
    var napMins: Int?

    enum CodingKeys: String, CodingKey {
        case sleepMins = "sleep_mins"
        case sleepEfficiencyPct = "sleep_efficiency_pct"
        case sleepDeepMins = "sleep_deep_mins"
        case sleepRemMins = "sleep_rem_mins"
        case timeInBedMins = "time_in_bed_mins"
        case sleepLightMins = "sleep_light_mins"
        case sleepAwakeMins = "sleep_awake_mins"
        case sleepLatencyMins = "sleep_latency_mins"
        case sleepAwakenings = "sleep_awakenings"
        case sleepStart = "sleep_start"
        case sleepEnd = "sleep_end"
        case napMins = "nap_mins"
    }
}

/// Overnight recovery (Fitbit)
struct Recovery: Codable, Hashable {
    /// Resting heart rate, computed overnight. A multi-day rise is the classic signature of under-recovery, illness, alcohol or accumulated stress.
    /// measures: the night that ended on this morning [bpm]
    var restingHrBpm: Int?
    /// Overnight heart-rate variability (RMSSD). Higher generally means better parasympathetic recovery. Meaningless in absolute terms — always read against my own baseline (see the baselines tab).
    /// measures: the night that ended on this morning [ms]
    var hrvMs: Double?
    /// RMSSD measured during deep sleep only — less contaminated by movement than the whole-night average.
    /// measures: the night that ended on this morning [ms]
    var hrvDeepSleepMs: Double?
    /// Randomness of heartbeat intervals. Higher entropy tends to indicate a more adaptable autonomic system.
    /// measures: the night that ended on this morning
    var hrvEntropy: Double?
    /// Average heart rate during non-REM sleep.
    /// measures: the night that ended on this morning [bpm]
    var nonRemHrBpm: Int?
    /// Average overnight blood-oxygen saturation. Healthy is ~95-100%; sustained dips can indicate disturbed breathing.
    /// measures: the night that ended on this morning [%]
    var spo2Pct: Double?
    /// Lower bound of the overnight SpO2 confidence interval — this is a distribution bound, not the night's minimum reading.
    /// measures: the night that ended on this morning [%]
    var spo2LowerPct: Double?
    /// Upper bound of the overnight SpO2 confidence interval.
    /// measures: the night that ended on this morning [%]
    var spo2UpperPct: Double?
    /// Average overnight breathing rate. Stable per person; a rise of 1-2 breaths/min often precedes illness.
    /// measures: the night that ended on this morning [breaths/min]
    var respiratoryRateBrpm: Double?
    /// Absolute overnight skin temperature. On its own this is noise — ambient conditions dominate. Use skin_temp_dev.
    /// measures: the night that ended on this morning [C]
    var skinTempC: Double?
    /// Deviation of skin temperature from my own 30-day baseline. THIS is the signal: a positive deviation tracks illness, alcohol and poor recovery. Blank until Fitbit has 30 days of history to build the baseline from.
    /// measures: the night that ended on this morning [C]
    var skinTempDev: Double?

    enum CodingKeys: String, CodingKey {
        case restingHrBpm = "resting_hr_bpm"
        case hrvMs = "hrv_ms"
        case hrvDeepSleepMs = "hrv_deep_sleep_ms"
        case hrvEntropy = "hrv_entropy"
        case nonRemHrBpm = "non_rem_hr_bpm"
        case spo2Pct = "spo2_pct"
        case spo2LowerPct = "spo2_lower_pct"
        case spo2UpperPct = "spo2_upper_pct"
        case respiratoryRateBrpm = "respiratory_rate_brpm"
        case skinTempC = "skin_temp_c"
        case skinTempDev = "skin_temp_dev"
    }
}

/// Activity & energy (Fitbit)
struct Activity: Codable, Hashable {
    /// Total energy expenditure: basal metabolism plus all activity. Measured, not estimated. Pair with total_cals_in for true energy balance — this is the number the whole system exists to produce.
    /// measures: 00:00-24:00 on this date [kcal]
    var totalCalsOut: Int?
    /// Total steps taken on this calendar day.
    /// measures: 00:00-24:00 on this date [count]
    var steps: Int?
    /// Distance covered on this calendar day.
    /// measures: 00:00-24:00 on this date [km]
    var distanceKm: Double?
    /// Energy burned above basal metabolism (the movement part of total_cals_out).
    /// measures: 00:00-24:00 on this date [kcal]
    var activeCals: Int?
    /// Total active minutes across all intensity levels.
    /// measures: 00:00-24:00 on this date [min]
    var totalActiveMins: Int?
    /// Active minutes at light intensity.
    /// measures: 00:00-24:00 on this date [min]
    var activeMinsLight: Int?
    /// Active minutes at moderate intensity.
    /// measures: 00:00-24:00 on this date [min]
    var activeMinsModerate: Int?
    /// Active minutes at vigorous intensity.
    /// measures: 00:00-24:00 on this date [min]
    var activeMinsVigorous: Int?
    /// Active Zone Minutes in the fat-burn heart-rate zone.
    /// measures: 00:00-24:00 on this date [min]
    var azmFatBurnMins: Int?
    /// Active Zone Minutes in the cardio heart-rate zone.
    /// measures: 00:00-24:00 on this date [min]
    var azmCardioMins: Int?
    /// Active Zone Minutes in the peak heart-rate zone.
    /// measures: 00:00-24:00 on this date [min]
    var azmPeakMins: Int?
    /// Minutes spent sedentary (excludes sleep).
    /// measures: 00:00-24:00 on this date [min]
    var sedentaryMins: Int?
    /// Lowest heart rate recorded across the day.
    /// measures: 00:00-24:00 on this date [bpm]
    var hrMinBpm: Int?
    /// Average heart rate across the day.
    /// measures: 00:00-24:00 on this date [bpm]
    var hrAvgBpm: Int?
    /// Peak heart rate recorded across the day.
    /// measures: 00:00-24:00 on this date [bpm]
    var hrMaxBpm: Int?
    /// Minutes with heart rate in the light zone. Note this counts most of a resting day, so it is a weak signal on its own.
    /// measures: 00:00-24:00 on this date [min]
    var minsHrLight: Int?
    /// Minutes with heart rate in the moderate zone.
    /// measures: 00:00-24:00 on this date [min]
    var minsHrModerate: Int?
    /// Minutes with heart rate in the vigorous zone.
    /// measures: 00:00-24:00 on this date [min]
    var minsHrVigorous: Int?
    /// Minutes with heart rate in the peak zone.
    /// measures: 00:00-24:00 on this date [min]
    var minsHrPeak: Int?
    /// Swim strokes counted on this day (blank on non-swim days).
    /// measures: 00:00-24:00 on this date [count]
    var swimStrokes: Int?

    enum CodingKeys: String, CodingKey {
        case totalCalsOut = "total_cals_out"
        case steps = "steps"
        case distanceKm = "distance_km"
        case activeCals = "active_cals"
        case totalActiveMins = "total_active_mins"
        case activeMinsLight = "active_mins_light"
        case activeMinsModerate = "active_mins_moderate"
        case activeMinsVigorous = "active_mins_vigorous"
        case azmFatBurnMins = "azm_fat_burn_mins"
        case azmCardioMins = "azm_cardio_mins"
        case azmPeakMins = "azm_peak_mins"
        case sedentaryMins = "sedentary_mins"
        case hrMinBpm = "hr_min_bpm"
        case hrAvgBpm = "hr_avg_bpm"
        case hrMaxBpm = "hr_max_bpm"
        case minsHrLight = "mins_hr_light"
        case minsHrModerate = "mins_hr_moderate"
        case minsHrVigorous = "mins_hr_vigorous"
        case minsHrPeak = "mins_hr_peak"
        case swimStrokes = "swim_strokes"
    }
}

/// Nutrition (meals roll-up)
struct Nutrition: Codable, Hashable {
    /// total_cals_in - total_cals_out. Positive is a surplus, negative a deficit. Blank unless both sides exist. The single most important derived number here: body composition should track this over weeks, and the outcome shows up on the FOLLOWING day's weigh-in, not this row's.
    /// measures: food eaten 05:00 this day -> 05:00 next day [kcal]
    var energyBalanceKcal: Int?
    /// Total energy eaten across the waking day (05:00 to 05:00, so a midnight snack counts toward the day it belongs to). Only written once the day is over — never a partial total.
    /// measures: food eaten 05:00 this day -> 05:00 next day [kcal]
    var totalCalsIn: Double?
    /// Total protein. The macro that most affects whether weight change is muscle or fat.
    /// measures: food eaten 05:00 this day -> 05:00 next day [g]
    var totalProteinG: Double?
    /// Total carbohydrate.
    /// measures: food eaten 05:00 this day -> 05:00 next day [g]
    var totalCarbsG: Double?
    /// Total fat.
    /// measures: food eaten 05:00 this day -> 05:00 next day [g]
    var totalFatG: Double?
    /// Total dietary fibre eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [g]
    var totalFiberG: Double?
    /// Total sugars eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [g]
    var totalSugarG: Double?
    /// Total saturated fat eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [g]
    var totalSaturatedFatG: Double?
    /// Total sodium eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [mg]
    var totalSodiumMg: Double?
    /// Total potassium eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [mg]
    var totalPotassiumMg: Double?
    /// Total calcium eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [mg]
    var totalCalciumMg: Double?
    /// Total iron eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [mg]
    var totalIronMg: Double?
    /// Total magnesium eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [mg]
    var totalMagnesiumMg: Double?
    /// Total zinc eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [mg]
    var totalZincMg: Double?
    /// Total vitamin C eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [mg]
    var totalVitaminCMg: Double?
    /// Total vitamin D eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [ug]
    var totalVitaminDUg: Double?
    /// Total vitamin B12 eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [ug]
    var totalVitaminB12Ug: Double?
    /// Total vitamin A eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [ug]
    var totalVitaminAUg: Double?
    /// Total folate eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [ug]
    var totalFolateUg: Double?
    /// Total omega-3 fatty acids eaten across the waking day, summed from the per-ingredient breakdown in the meals tab.
    /// measures: food eaten 05:00 this day -> 05:00 next day [g]
    var totalOmega3G: Double?

    enum CodingKeys: String, CodingKey {
        case energyBalanceKcal = "energy_balance_kcal"
        case totalCalsIn = "total_cals_in"
        case totalProteinG = "total_protein_g"
        case totalCarbsG = "total_carbs_g"
        case totalFatG = "total_fat_g"
        case totalFiberG = "total_fiber_g"
        case totalSugarG = "total_sugar_g"
        case totalSaturatedFatG = "total_saturated_fat_g"
        case totalSodiumMg = "total_sodium_mg"
        case totalPotassiumMg = "total_potassium_mg"
        case totalCalciumMg = "total_calcium_mg"
        case totalIronMg = "total_iron_mg"
        case totalMagnesiumMg = "total_magnesium_mg"
        case totalZincMg = "total_zinc_mg"
        case totalVitaminCMg = "total_vitamin_c_mg"
        case totalVitaminDUg = "total_vitamin_d_ug"
        case totalVitaminB12Ug = "total_vitamin_b12_ug"
        case totalVitaminAUg = "total_vitamin_a_ug"
        case totalFolateUg = "total_folate_ug"
        case totalOmega3G = "total_omega3_g"
    }
}

/// Body composition (scale screenshot)
struct Body: Codable, Hashable {
    /// Body weight. Direction is deliberately neutral — whether up is good depends on a goal this data doesn't contain. Day-to-day swings are mostly water; read the trend, not the delta.
    /// measures: measured on this morning, fasted [kg]
    var weightKg: Double?
    /// Body mass index as computed by the scale. Low information given body fat and lean mass are measured directly.
    /// measures: measured on this morning, fasted
    var bmi: Double?
    /// Body fat percentage from bioimpedance. Hydration-sensitive, so trust the multi-day trend over any single reading.
    /// measures: measured on this morning, fasted [%]
    var bodyFatPct: Double?
    /// Fat stored under the skin, as a percentage.
    /// measures: measured on this morning, fasted [%]
    var subcutaneousFatPct: Double?
    /// Visceral fat index (a unitless scale value, not a percentage or a mass). Fat around the organs; the most metabolically relevant fat measure here.
    /// measures: measured on this morning, fasted [index]
    var visceralFat: Double?
    /// Total body water. Explains much of the day-to-day noise in weight and body-fat readings.
    /// measures: measured on this morning, fasted [%]
    var bodyWaterPct: Double?
    /// Skeletal muscle mass. Should hold or rise while weight falls — that is what successful recomposition looks like.
    /// measures: measured on this morning, fasted [kg]
    var muscleMassKg: Double?
    /// Bone mass. Changes very slowly; effectively a constant.
    /// measures: measured on this morning, fasted [kg]
    var boneMassKg: Double?
    /// Basal metabolic rate as estimated by the scale from lean mass. Compare against Fitbit's measured total_cals_out.
    /// measures: measured on this morning, fasted [kcal]
    var bmrKcal: Double?
    /// The scale's proprietary 'metabolic age' estimate. Vendor marketing metric — low scientific value; kept for completeness.
    /// measures: measured on this morning, fasted [years]
    var metabolicAge: Double?
    /// weight_kg x (1 - body_fat_pct/100). Everything that isn't fat. The number that should stay flat while you cut.
    /// measures: measured on this morning, fasted [kg]
    var leanMassKg: Double?
    /// Local timestamp of the weigh-in, read off the app screen. The hour is signal: a fasted 07:00 reading and a 21:00 one are not comparable.
    /// measures: measured on this morning, fasted
    var bodyMeasuredAt: String?

    enum CodingKeys: String, CodingKey {
        case weightKg = "weight_kg"
        case bmi = "bmi"
        case bodyFatPct = "body_fat_pct"
        case subcutaneousFatPct = "subcutaneous_fat_pct"
        case visceralFat = "visceral_fat"
        case bodyWaterPct = "body_water_pct"
        case muscleMassKg = "muscle_mass_kg"
        case boneMassKg = "bone_mass_kg"
        case bmrKcal = "bmr_kcal"
        case metabolicAge = "metabolic_age"
        case leanMassKg = "lean_mass_kg"
        case bodyMeasuredAt = "body_measured_at"
    }
}

/// One day. `date` is the local civil day (Europe/Lisbon).
struct HealthDay: Codable, Hashable, Identifiable {
    var id: String { date }
    var date: String
    var selfReport: SelfReport?
    var sleep: Sleep?
    var recovery: Recovery?
    var activity: Activity?
    var nutrition: Nutrition?
    var body: Body?

    enum CodingKeys: String, CodingKey {
        case date
        case selfReport = "self_report"
        case sleep = "sleep"
        case recovery = "recovery"
        case activity = "activity"
        case nutrition = "nutrition"
        case body = "body"
    }
}

/// The GET /daily envelope.
struct DailyResponse: Codable {
    var from: String
    var to: String
    var count: Int
    var blocks: [String]
    var days: [HealthDay]
}
