"""Emit the schema in other languages' terms, from the one registry.

    python -m src.schema_export swift   > HealthTypes.swift
    python -m src.schema_export sql     > schema.sql
    python -m src.schema_export json    > schema.json
    python -m src.schema_export markdown

These are **files it emits, not systems it creates**. Nothing here connects to a
database or an app; it exists so that the day you want either, the schema doesn't
have to be retyped by hand and drift from the source of truth on the first change.

`swift` is the one with a job today: paste it into the iOS app and the app's model
layer is, by construction, exactly the sheet's schema.
"""
from __future__ import annotations

import json
import sys
from typing import Dict, List

from schema.registry import (
    BLOCK_LABELS, BLOCKS, CAUSAL_LABELS, DAILY_COLUMNS, Column, columns_in,
)

_SWIFT_TYPES: Dict[str, str] = {
    "date": "String", "datetime": "String", "time": "String",
    "number": "Double", "integer": "Int", "boolean": "Bool", "string": "String",
}

_SQL_TYPES: Dict[str, str] = {
    "date": "DATE", "datetime": "TIMESTAMPTZ", "time": "TEXT",
    "number": "DOUBLE PRECISION", "integer": "INTEGER", "boolean": "BOOLEAN",
    "string": "TEXT",
}


def _pascal(block: str) -> str:
    return "".join(part.capitalize() for part in block.split("_"))


def _camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part.capitalize() for part in rest)


def swift() -> str:
    """Codable structs mirroring the /daily response, one per block.

    Every field is Optional — and that is not defensiveness, it is the truth: a day
    with no weigh-in genuinely has no body composition, and a `0` there would be a
    lie the UI would happily chart.
    """
    out: List[str] = [
        "// Generated by `python -m src.schema_export swift` — do not edit.",
        "// Mirrors GET /daily on the health-tracker-ingest service.",
        "// Every field is Optional because a blank cell means NOT MEASURED, which",
        "// is different from zero — never default these to 0.",
        "",
        "import Foundation",
        "",
    ]
    blocks = [b for b in BLOCKS if b not in ("key", "meta")]
    for block in blocks:
        cols = columns_in(block)
        out.append(f"/// {BLOCK_LABELS[block]}")
        out.append(f"struct {_pascal(block)}: Codable, Hashable {{")
        for c in cols:
            out.append(f"    /// {c.description.splitlines()[0]}")
            unit = f" [{c.unit}]" if c.unit else ""
            out.append(f"    /// measures: {CAUSAL_LABELS[c.causal]}{unit}")
            out.append(f"    var {_camel(c.name)}: {_SWIFT_TYPES[c.dtype]}?")
        out.append("")
        out.append("    enum CodingKeys: String, CodingKey {")
        for c in cols:
            out.append(f'        case {_camel(c.name)} = "{c.name}"')
        out.append("    }")
        out.append("}")
        out.append("")

    out.append("/// One day. `date` is the local civil day (Europe/Lisbon).")
    out.append("struct HealthDay: Codable, Hashable, Identifiable {")
    out.append("    var id: String { date }")
    out.append("    var date: String")
    for block in blocks:
        out.append(f"    var {_camel(block)}: {_pascal(block)}?")
    out.append("")
    out.append("    enum CodingKeys: String, CodingKey {")
    out.append('        case date')
    for block in blocks:
        out.append(f'        case {_camel(block)} = "{block}"')
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("/// The GET /daily envelope.")
    out.append("struct DailyResponse: Codable {")
    out.append("    var from: String")
    out.append("    var to: String")
    out.append("    var count: Int")
    out.append("    var blocks: [String]")
    out.append("    var days: [HealthDay]")
    out.append("}")
    return "\n".join(out) + "\n"


def sql() -> str:
    """DDL for the day this outgrows a spreadsheet. It does not today: a decade of
    data is ~69 MB. Comments carry the unit and causal window so the semantics
    survive the migration rather than being lost with the registry."""
    lines: List[str] = [
        "-- Generated by `python -m src.schema_export sql` — do not edit.",
        "-- One row per local civil day. Deliberately WIDE: every column is 1:1",
        "-- with `date`, so splitting this into per-category tables would add a",
        "-- join and remove nothing (it would not be normalisation).",
        "",
        "CREATE TABLE IF NOT EXISTS daily_summary (",
    ]
    body: List[str] = []
    for c in DAILY_COLUMNS:
        null = " PRIMARY KEY" if c.name == "date" else ""
        body.append(f"    {c.name:26s} {_SQL_TYPES[c.dtype]}{null}")
    lines.append(",\n".join(body))
    lines.append(");")
    lines.append("")
    for c in DAILY_COLUMNS:
        note = c.description.replace("'", "''").replace("\n", " ")
        unit = f"[{c.unit}] " if c.unit else ""
        lines.append(
            f"COMMENT ON COLUMN daily_summary.{c.name} IS "
            f"'{unit}({CAUSAL_LABELS[c.causal]}) {note}';")
    return "\n".join(lines) + "\n"


def as_json() -> str:
    """The registry itself, for any consumer that wants to introspect it."""
    return json.dumps({
        "blocks": [{"name": b, "label": BLOCK_LABELS[b]} for b in BLOCKS],
        "columns": [{
            "name": c.name, "block": c.block, "type": c.dtype, "unit": c.unit,
            "source": c.source, "measures_when": CAUSAL_LABELS[c.causal],
            "causal_role": c.role, "direction": c.direction, "tier": c.tier,
            "min": c.range[0] if c.range else None,
            "max": c.range[1] if c.range else None,
            "description": c.description,
        } for c in DAILY_COLUMNS],
    }, indent=2, ensure_ascii=False) + "\n"


def markdown() -> str:
    """A human-readable dictionary, for the repo docs."""
    out = ["# `daily_summary` columns", "",
           "Generated from `schema/registry.py`. Do not edit by hand.", ""]
    for block in BLOCKS:
        cols = columns_in(block)
        if not cols:
            continue
        out.append(f"## {BLOCK_LABELS[block]}")
        out.append("")
        out.append("| column | type | unit | measures | direction | description |")
        out.append("|---|---|---|---|---|---|")
        for c in cols:
            desc = c.description.replace("\n", " ")
            out.append(f"| `{c.name}` | {c.dtype} | {c.unit or '—'} | "
                       f"{CAUSAL_LABELS[c.causal]} | {c.direction} | {desc} |")
        out.append("")
    return "\n".join(out)


_FORMATS = {"swift": swift, "sql": sql, "json": as_json, "markdown": markdown}


def main() -> None:
    fmt = sys.argv[1] if len(sys.argv) > 1 else ""
    if fmt not in _FORMATS:
        sys.exit(f"usage: python -m src.schema_export [{'|'.join(_FORMATS)}]")
    sys.stdout.write(_FORMATS[fmt]())


if __name__ == "__main__":
    main()
